# Generated by Django 6.0.1 on 2026-01-30 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScheduleResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="当前使用"),
                ),
                (
                    "solve_status",
                    models.CharField(
                        choices=[
                            ("OPTIMAL", "最优解"),
                            ("FEASIBLE", "可行解"),
                            ("INFEASIBLE", "无可行解"),
                            ("MODEL_INVALID", "模型无效"),
                            ("UNKNOWN", "未知"),
                        ],
                        default="UNKNOWN",
                        max_length=20,
                        verbose_name="求解状态",
                    ),
                ),
                (
                    "solve_time_ms",
                    models.IntegerField(default=0, verbose_name="求解耗时(ms)"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="备注")),
            ],
            options={
                "verbose_name": "排课结果",
                "verbose_name_plural": "排课结果",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ScheduleEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day", models.IntegerField(verbose_name="星期")),
                ("period", models.IntegerField(verbose_name="节次")),
                ("is_locked", models.BooleanField(default=False, verbose_name="锁定")),
                (
                    "school_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.schoolclass",
                        verbose_name="班级",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.subject",
                        verbose_name="课程",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.teacher",
                        verbose_name="教师",
                    ),
                ),
                (
                    "result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="scheduler.scheduleresult",
                        verbose_name="排课结果",
                    ),
                ),
            ],
            options={
                "verbose_name": "课表条目",
                "verbose_name_plural": "课表条目",
                "indexes": [
                    models.Index(
                        fields=["result", "school_class"],
                        name="scheduler_s_result__b5ae1f_idx",
                    ),
                    models.Index(
                        fields=["result", "teacher"],
                        name="scheduler_s_result__55b239_idx",
                    ),
                    models.Index(
                        fields=["result", "day", "period"],
                        name="scheduler_s_result__434b35_idx",
                    ),
                ],
            },
        ),
    ]
