# Generated by Django 6.0.1 on 2026-03-26 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_scheduleresult_combined_class_assignments'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleresult',
            name='name',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='结果名称'),
        ),
    ]
