# Generated by Django 6.0.1 on 2026-01-30 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="classsubjectteacher",
            name="is_manual",
            field=models.BooleanField(
                default=True,
                help_text="手动指定的分配不会被自动分配覆盖",
                verbose_name="手动指定",
            ),
        ),
        migrations.CreateModel(
            name="TeacherQualification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=0, help_text="数字越大优先级越高", verbose_name="优先级"
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qualified_teachers",
                        to="core.subject",
                        verbose_name="课程",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qualifications",
                        to="core.teacher",
                        verbose_name="教师",
                    ),
                ),
            ],
            options={
                "verbose_name": "教师资质",
                "verbose_name_plural": "教师资质",
                "unique_together": {("teacher", "subject")},
            },
        ),
    ]
