# Generated by Django 6.0.1 on 2026-01-30 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_classsubjectteacher_is_manual_teacherqualification"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teacherqualification",
            name="priority",
        ),
    ]
