# Generated by Django 6.0.1 on 2026-01-31 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_restore_combined_class_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="max_weekly_hours",
            field=models.IntegerField(
                blank=True,
                help_text="留空表示不限制",
                null=True,
                verbose_name="周课时上限",
            ),
        ),
    ]
