# Generated by Django 6.0.1 on 2026-01-31 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_teacher_max_weekly_hours"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="must_reach_max_hours",
            field=models.BooleanField(
                default=False,
                help_text="勾选后，排课时必须达到周课时上限",
                verbose_name="必须达到上限",
            ),
        ),
    ]
