# Generated by Django 6.0.1 on 2026-01-31 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_schedulersettings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedulersettings",
            name="s6_subject_switch_weight",
            field=models.IntegerField(
                default=5,
                help_text="教师连续两节在不同班级上课的惩罚分",
                verbose_name="换班惩罚权重",
            ),
        ),
    ]
