# Generated by Django 5.2.1

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_schedulersettings_s6_subject_switch_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='max_teacher_classes',
            field=models.IntegerField(default=1, help_text='同一教师最多可教几个班的该课程(1~5)', verbose_name='单师最多班数'),
        ),
    ]
