# Generated by Django 5.2.1

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_subject_max_teacher_classes'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulersettings',
            name='s7_same_class_subject_switch_weight',
            field=models.IntegerField(default=3, help_text='教师连续两节在同一班级但上不同科目的惩罚分', verbose_name='同班换科惩罚权重'),
        ),
    ]
