# Generated by Django 5.2.1

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_schedulersettings_s7_same_class_subject_switch_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulersettings',
            name='class_meeting_name',
            field=models.CharField(default='班会', help_text='班会课的课程名称，如"班会"、"班队会"、"主题班会"等', max_length=50, verbose_name='班会课程名'),
        ),
        migrations.AddField(
            model_name='schedulersettings',
            name='combined_class_slots',
            field=models.CharField(default='1,4;1,5;3,4;3,5', help_text='校本课程/合班课的时段，格式"星期,节次"用分号分隔，如"1,4;1,5;3,4;3,5"表示周二下午和周四下午', max_length=100, verbose_name='合班课时段'),
        ),
        migrations.AddField(
            model_name='schedulersettings',
            name='solver_num_workers',
            field=models.IntegerField(default=4, help_text='并行计算的线程数，建议设为CPU核心数', verbose_name='求解器线程数'),
        ),
    ]
