# Generated by Django 6.0.1 on 2026-03-19 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_teacher_combined_class_day"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeacherBlockedTime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day",
                    models.IntegerField(
                        choices=[
                            (0, "周一"),
                            (1, "周二"),
                            (2, "周三"),
                            (3, "周四"),
                            (4, "周五"),
                        ],
                        verbose_name="星期",
                    ),
                ),
                (
                    "period_type",
                    models.CharField(
                        choices=[("am", "上午"), ("pm", "下午"), ("all", "全天")],
                        max_length=3,
                        verbose_name="时段",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocked_times",
                        to="core.teacher",
                        verbose_name="教师",
                    ),
                ),
            ],
            options={
                "verbose_name": "教师禁排时段",
                "verbose_name_plural": "教师禁排时段",
                "unique_together": {("teacher", "day", "period_type")},
            },
        ),
    ]
