# Generated by Django 6.0.1 on 2026-06-24 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_alter_schedulersettings_h9_consecutive_forbidden"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedulersettings",
            name="h14_homeroom_main_subject",
            field=models.BooleanField(
                default=True,
                help_text="开启后，每个班级的班主任必须在本班至少担任一门主课，否则排课失败",
                verbose_name="班主任必须担任主课",
            ),
        ),
    ]
